// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  circle: string;
  innerCircle: string;
  inner_circle: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
