// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'safe-area': string;
  safeArea: string;
}
declare const cssExports: CssExports;
export default cssExports;
